### ISSUE TITLE
How to use the foreach block to filter the list which match a Regex?

### ISSUE THREAD

**Issue by a14907** [postmanlabs/labs-docs#46]
It really confuse me.I use these block show blow, It does not work.

![捕获](https://user-images.githubusercontent.com/13792421/199159417-6e073766-1aac-4b74-a88c-e356d41f4fd1.JPG)

The list is some string:

![捕获](https://user-images.githubusercontent.com/13792421/199159505-6683df4c-3c5f-41ba-8250-cb69036ce929.JPG)

I want to output the first and second item, and do not output third item.

but it does output only one item, as show.

so what is the problem? how to use the foreach and regex block?

**Comment by DanielKimmelmann1** [comment]
Hi @a14907 the reason this happens is because the `regex` block only sends it's data the first iteration of the loop, since it is not a part of the `for each`. The solution to this is to use a `create data` block, which has a signal port, which means it can be hooked up to the `for each` to fire with every iteration and give you an output for each value. See the below image:

<img width="1192" alt="Screen Shot 2022-11-09 at 9 05 35 AM" src="https://user-images.githubusercontent.com/116036032/200904268-0c6a4d9d-7ce5-4f13-85b0-60ab2926bc4d.png">
 
The only thing I changed from your Flow is swapping the `regex` block for a `create data` block and then adding a connection from the output of the `for each` loop to the signal port of the `create data` block so that it fires it's pattern each iteration.

**Comment by a14907** [comment]
perfect！ 
It works！
